---
- name: restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
  listen: restart zabbix-agent

- name: reload zabbix-agent
  systemd:
    name: zabbix-agent
    state: reloaded
  listen: reload zabbix-agent
