name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  ansible_deploy:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install community.crypto collection
        run: ansible-galaxy collection install community.crypto

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Prepare Vault password
        run: |
          echo "${{ secrets.VAULT_PASSWORD }}" > ansible/.vault
          chmod 600 ansible/.vault

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -vv -i inventory/inventory.yaml playbook.yaml --vault-password-file .vault | tee execution.log

      - name: Clean up secrets
        run: |
          rm -f ~/.ssh/id_rsa ansible/.vault

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: execution-logs
          path: ansible/execution.log
